### ISSUE TITLE
Needs support for Realm 1.0.2

### ISSUE THREAD

**Issue by jpsanabria** [realm/realm-cocoa-converter#18]
I have attempted to include the converter into a new Realm project but discovered that a good portion of the library uses different syntax than is currently used in Realm 1.0.2.

Things such as RLMArray no longer exist for example. When is this being updated or do you have a guide for how to update it?

**Comment by jpsanabria** [comment]
Just found out that Realm Converter doesn't even support iOS.. This explains everything

**Comment by stel** [comment]
RealmConverted was updated to use Realm 2.0.2 in #33, iOS support is tracked in #9, closing this issue.
